# zmodload zsh/zprof

DEFAULT_USER=whoami``

#
# https://gist.github.com/ctechols/ca1035271ad134841284
# https://carlosbecker.com/posts/speeding-up-zsh
#
autoload -Uz compinit
case $SYSTEM in
  Darwin)
    if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
      compinit;
    else
      compinit -C;
    fi
    ;;
  Linux)
    # not yet match GNU & BSD stat
  ;;
esac
_comp_options+=(globdots)

autoload -U promptinit; promptinit
prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT "
PROMPT='%(?.%F{magenta}.%F{red}❯%F{magenta})❯%f '

HISTSIZE=10000
SAVEHIST=10000
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

# Enable autocorrect
setopt CORRECT_ALL

# fixes ^w word delete
autoload -U select-word-style
select-word-style bash

# jum ower words
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Load stuff
source ~/.zsh_env_vars
# source ~/.zsh_terragrunt_vars
source ~/.zsh_git_aliases

# zstyle
# zstyle :prompt:pure:path color default
# zstyle :prompt:pure:git:stash show yes

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Alias
alias vi="/usr/local/bin/nvim"
alias sr="ssh -o StrictHostKeyChecking=no -l root $@"
alias p2="ping -i0.2 $@"
alias ll="ls -la $@"

# pyenv
alias pyinit='eval "$(pyenv init -)"'

# rbenv
export PATH="/Users/sirup/.rbenv/bin:$PATH"
alias rbinit='eval "$(rbenv init -)"'
# eval "$(rbenv init -)"

# goenv
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
alias goinit='eval "$(goenv init -)"'

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

#zprof

