config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_config_nvim_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_fzf.zsh:
    dst: ~/.fzf.zsh
    src: fzf.zsh
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  Simonass-Air.lan:
    dotfiles:
    - f_zshrc
    - f_fzf.zsh
    - f_config_nvim_init.vim
  Simonass-MacBook-Pro.local:
    dotfiles:
    - f_zshrc
    - f_fzf.zsh
    - f_config_nvim_init.vim
