config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  Simonass-Air.lan:
    dotfiles:
    - f_zshrc
