config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
  link_on_import: nolink
dotfiles:
  d_vim:
    dst: ~/.vim
    src: vim
  f_fzf.zsh:
    dst: ~/.fzf.zsh
    src: fzf.zsh
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore:
    dst: ~/.gitignore
    src: gitignore
  f_overcommit.yml:
    dst: ~/.overcommit.yml
    src: overcommit.yml
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_config_nvim_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_config_kitty_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
profiles:
  Simonass-Air.lan:
    dotfiles:
    - f_zshrc
    - f_fzf.zsh
    - f_config_nvim_init.vim
  Simonass-MacBook-Pro.local:
    dotfiles:
    - f_zshrc
    - f_fzf.zsh
    - f_config_nvim_init.vim
    - f_gitconfig
    - f_gitignore
    - d_vim
    - f_overcommit.yml
    - f_config_kitty_kitty.conf
  Simonass-MBP.lan:
    include:
    - Simonass-MacBook-Pro.local
