config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
  link_on_import: nolink
dotfiles:
  f_fzf.zsh:
    dst: ~/.fzf.zsh
    src: fzf.zsh
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore:
    dst: ~/.gitignore
    src: gitignore
  f_overcommit.yml:
    dst: ~/.overcommit.yml
    src: overcommit.yml
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_config_nvim_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_config_kitty_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_gitignore_global:
    src: gitignore_global
    dst: ~/.gitignore_global
  f_zsh_git_aliases:
    src: zsh_git_aliases
    dst: ~/.zsh_git_aliases
  d_hammerspoon:
    src: hammerspoon
    dst: ~/.hammerspoon
profiles:
  Simonass-Air.lan:
    dotfiles:
    - f_zshrc
    - f_fzf.zsh
    - f_config_nvim_init.vim
    - f_config_kitty_kitty.conf
  Simonass-MacBook-Pro.local:
    dotfiles:
    - f_zshrc
    - f_fzf.zsh
    - f_config_nvim_init.vim
    - f_gitconfig
    - f_gitignore
    - f_overcommit.yml
    - f_config_kitty_kitty.conf
    - f_gitignore_global
    - f_zsh_git_aliases
    - d_hammerspoon
  Simonass-MBP.lan:
    include:
    - Simonass-MacBook-Pro.local
  Simonass-MacBook-Pro-3.local:
    include:
    - Simonass-MacBook-Pro.local
  Simonass-MacBook-Air.local:
    include:
    - Simonass-MacBook-Pro.local
  QP3JHGWT0V:
    include:
    - Simonass-MacBook-Pro.local
